name: sylph
version: 1.0.0+1
publish_to: none
description: Sylph — Weather & Air

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.0
  connectivity_plus: ^4.0.0
  flutter_local_notifications: ^14.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Boldonse
      fonts:
        - asset: assets/fonts/Boldonse-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/sylph.png"
  adaptive_icon_background: "#0a0a0f"
  adaptive_icon_foreground: "assets/icon/sylph_foreground.png"
